version: '2'
services:
    fed-proxy:
        image: onitsoft/nexchange-fed-proxy
        volumes:
            - /nexchange/root:/nexchange/root
        ports:
            - "3000:3000"
        environment:
            - NEXCHANGE_ROOT=/nexchange/root/nexchange
            - ICO_ROOT=/nexchange/root/ico
        depends_on:
            - react-client
            - ico-page
        restart: always    
    web:
        image: onitsoft/nginx:node
        volumes:
            - /nexchange/etc/letsencrypt:/etc/letsencrypt
            - /nexchange/etc/nginx/ssl:/etc/nginx/ssl
            - /nexchange/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /nexchange/etc/nginx/.htpasswd:/etc/nginx/.htpasswd
            - /nexchange/root:/nexchange/root
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - fed-proxy
        restart: always
    react-client:
        image: onitsoft/nexchange-open-client-react
        volumes:
            - /nexchange/root/nexchange:/deploy/app/build
        entrypoint: sleep infinity
        restart: always
    ico-page:
        image: onitsoft/ico-landing-page
        volumes:
            - /nexchange/root/ico:/deploy/app/build
        entrypoint: sleep infinity
        restart: always
